#pragma once

#include "block/block.h"
#include "comp_unit/comp_unit.h"
#include "exp/binary_exp/binary_exp.h"
#include "exp/unary_exp/unary_exp.h"
#include "func/func_def.h"
#include "lval/lval.h"
#include "number/number.h"
#include "start/start.h"
#include "stmts/block_stmt/block_stmt.h"
#include "stmts/ret_stmt/ret_stmt.h"
#include "stmt/stmt.h"
#include "var/var_def.h"
#include "var/var_def_list.h"